### ISSUE TITLE
Frequent 502 Bad Gateway

### ISSUE THREAD

**Issue by nicksunderland** [MRCIEU/opengwas-api#13]
<img width="269" alt="Screenshot 2023-12-15 at 23 18 51" src="https://github.com/MRCIEU/opengwas-api/assets/44629106/ced08044-c928-4826-a196-eba6758a3b45">

I'm frequently getting issues with the API (502 error), and even just logging on to the [API page](https://gwas-api.mrcieu.ac.uk/) fails frequently. It's been an issue for a few weeks on my machine. Is it just my set up?

Best 
Nick

**Comment by remlapmot** [comment]
It's possible the server was down/too busy or since Gib setup fail2ban on the server, which blocks IP addresses making very frequent requests you may accidentally be blocked. 

If that's the case @explodecomputer would need to unblock your IP address.
