### ISSUE TITLE
Gene variant API returns 503 error for specific genes

### ISSUE THREAD

**Issue by Z-Zen** [MRCIEU/opengwas-api#16]
Hi!

I would like to report an error from the API which returns the error `503` for two specific genes: `ENSG00000111684` and `ENSG00000004139`

![image](https://github.com/user-attachments/assets/4edccff5-7e36-409e-9d60-8466122461a9)

Could you please tell me what might be the problem?

Thank you!

**Comment by JasonQiu** [comment]
Reproduced. Looking into it.
